FROM node:13-alpine

WORKDIR /home/node/app
RUN mkdir -p node_modules && chown -R node:node .

USER node

COPY --chown=node:node ./gemini-api-node/package.json .
RUN rm -f package-lock.json && yarn install --production=false

COPY --chown=node:node ./gemini-api-node .
COPY --chown=node:node ./gemini-dev-environment/.env-api ./.env

RUN rm -f package-lock.json && yarn install --production=false