FROM node:13-alpine

WORKDIR /home/node/app
RUN mkdir -p node_modules && chown -R node:node .

USER node

COPY --chown=node:node ./gemini-web-react/package.json .
RUN rm -f package-lock.json && yarn install --production=false

COPY --chown=node:node ./gemini-web-react .
COPY --chown=node:node ./gemini-dev-environment/.env-web ./.env

EXPOSE 3000