FROM node:13-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY ./gemini-web-react/package*.json ./

USER node

RUN npm install

COPY --chown=node:node ./gemini-web-react .
# COPY --chown=node:node ./gemini-dev-environment/webpack.common.js .
COPY --chown=node:node ./gemini-dev-environment/.env-web ./.env

EXPOSE 3000

CMD [ "npm", "start" ]
