FROM node:13-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY ./gemini-api-node/package.json ./

USER node

RUN npm install
RUN npm install --only=dev

COPY --chown=node:node ./gemini-api-node .
COPY --chown=node:node ./gemini-dev-environment/.env-api ./.env

EXPOSE 8000

CMD [ "npm", "start:dev" ]
